#!/bin/bash

# deploy
#
# Author: Jinhyuk Lee <eces at mstock.org>
# Organization: MINTPRESSO <support at mintpresso.com>
# Repository: https://github.com/eces/chai-latte
#

GREEN='\033[32m'
GREEN_B='\033[42m'
YELLOW='\033[33m'
BLINK='\033[5m'
RESET='\033[0m'

ITEM=1
ITEMS=5

PORT=$1

if [ -z "$PORT" ]
then
  echo -e "usage: deploy [port_number]\n"
  exit
fi

if ! [ -f deploy.conf ]
then
  echo -e "error:\tcannot find ${GREEN}deploy.conf${RESET}\n\tmake sure ${GREEN}`pwd`/deploy.conf${RESET} is in this directory\n"
  exit
fi

. ./deploy.conf

if [ -z "$ORGANIZATION_NAME" ]
then
  ORGANIZATION_NAME='DEPLOYMENT'
  echo -e "warn:\t${GREEN}ORGANIZATION_NAME${RESET} is unset\n\tconfigure this option in ${GREEN}deploy.conf${RESET}\n"
fi

if [ -z "$USER_NAME" ]
then
  USER_NAME=`whoami`
  echo -e "warn:\t${GREEN}USER_NAME${RESET} is unset\n\tconfigure this option in ${GREEN}deploy.conf${RESET}\n\t${GREEN}${USER_NAME}${RESET} will be used instead\n"
fi

if [ -z "$SERVER_NAME" ]
then
  SERVER_NAME='somewhere'
  echo -e "warn:\t${GREEN}SERVER_NAME${RESET} is unset\n\tconfigure this option in ${GREEN}deploy.conf${RESET}\n\t${GREEN}somewhere${RESET} will be used instead\n"
fi

if [ -z "$SERVER_HOST" ] || [ -z "$SERVER_USER" ] || [ -z "$BASE_DIR" ]
then
  echo -e "error:\t${GREEN}SERVER_HOST${RESET}, ${GREEN}SERVER_USER${RESET}, and ${GREEN}BASE_DIR${RESET} must be given\n\tconfigure this option in ${GREEN}deploy.conf${RESET}\n"
  exit
fi

function canceled {
  echo -e "${GREEN}\n[ $ORGANIZATION_NAME ] See you later :)${RESET}"
  exit
}

echo -e "\n[ $ORGANIZATION_NAME ]\n"
echo -e "Auto Deployment to ${GREEN}${SERVER_NAME}${RESET} will be processed in ${GREEN}$(pwd)${RESET}\n"


# see path of what you're going to deploy. is it right?
echo -e "[${ITEM}/${ITEMS}] clean-compile-staged ${GREEN}$(pwd)/target${RESET} is okay? [y/n]: "
  while true; do
    read OPT
    if [ "$OPT" = "n" ]; then
      canceled
    elif [ "$OPT" = "y" ]; then
      break
    else
      echo "[y/n] yes or no?"
    fi
  done
let ITEM+=1

# what server and port do you want to deploy?
echo -e "[${ITEM}/${ITEMS}] Port ${GREEN}${PORT}${RESET} is okay? [y/n]: "
  while true; do
    read OPT
    if [ "$OPT" = "n" ]; then
      canceled
    elif [ "$OPT" = "y" ]; then
      break
    else
      echo "[y/n] yes or no?"
    fi
  done
let ITEM+=1

if [ -f deploy.before ]
then
  echo -e $YELLOW
  . ./deploy.before
  echo -e $RESET
fi

echo -e "[${ITEM}/${ITEMS}] Waiting for upload ... "
  START=$(date +%s)

  # copying
  echo -e "${YELLOW}"
  rsync -rzu ./target/ $SERVER_USER@$SERVER_HOST:$BASE_DIR/.${PORT}
  RSYNC_CODE=$?
  echo -e "${RESET}"

  if [ $RSYNC_CODE -ne 0 ]
  then
    echo -e "error:\tfailed to upload\n\tcheck ${GREEN}${SERVER_USER}@${SERVER_HOST}${RESET} is correct\n"
    exit
  else
    END=$(date +%s)
    DIFF1=$[$END-$START]
    echo -e "${GREEN} Uploaded in ${DIFF1}s${RESET}"
  fi

let ITEM+=1
echo -e "[${ITEM}/${ITEMS}] Waiting for restart ... "
  # ssh shell script execution
  echo -e "${YELLOW}"
  START=$(date +%s)
  ssh -t -t ${SERVER_USER}@${SERVER_HOST} << EOF
cd ${BASE_DIR}
mkdir -p ${PORT}/framework
mkdir -p ${PORT}/logs
cd ${PORT}
if [ -f ${BASE_DIR}/${PORT}/RUNNING_PID ]
then
  kill \`cat ${BASE_DIR}/${PORT}/RUNNING_PID\`
fi
rm -rf framework/*
mv ../.${PORT}/* framework/
echo -e "[INFO] Deployed at \t$(date)\t$(date +%s) by ${USER_NAME}" >> ./logs/deployment.log
cd ./framework

nohup ./start -Dhttp.port=${PORT} ${PLAY_OPTIONS} & 1>> ./nohup.out
exit
EOF
  echo -e "${RESET}"
  END=$(date +%s)
  DIFF2=$[$END-$START]
  TOTAL=$[DIFF1+DIFF2]
  echo -e "${GREEN} Executed in ${DIFF2}s${RESET}\n Total ${TOTAL}s\n"

let ITEM+=1
echo -e "[${ITEM}/${ITEMS}] ${GREEN}DONE!${RESET}"

if [ -f deploy.after ]
then
  echo -e $YELLOW
  . ./deploy.after
  echo -e $RESET
fi